// import { LOGGED_OUT as logged_out } from '../auth/actionTypes';

export const LOADING_INVITATION_LIST = 'timeline/LOADING_INVITATION_LIST';
export const LOADING_FOOTER_INVITATION_LIST = 'timeline/LOADING_FOOTER_INVITATION_LIST';
export const INVITATION_LIST_AVAILABLE = 'timeline/INVITATION_LIST_AVAILABLE';
export const INVITATION_LIST_REFRESHED = 'timeline/INVITATION_LIST_REFRESHED';
export const ADD_USER = 'timeline/ADD_USER';
export const ADD_CONTEXT_ACTION = 'timeline/ADD_CONTEXT_ACTION';
export const ADD_EVENT = 'timeline/ADD_EVENT';

export const LOADING_CONTEXT_ACTION_LIST = 'timeline/LOADING_CONTEXT_ACTION_LIST';
export const CONTEXT_ACTION_LIST_AVAILABLE = 'timeline/CONTEXT_ACTION_LIST_AVAILABLE';
export const LOADING_EVENT_LIST = 'timeline/LOADING_EVENT_LIST';
export const LOADING_FOOTER_EVENT_LIST = 'timeline/LOADING_FOOTER_EVENT_LIST';
export const EVENT_LIST_AVAILABLE = 'timeline/EVENT_LIST_AVAILABLE';
export const LOADING_HEADER = 'timeline/LOADING_HEADER';

export const LOADING_CREATE_INVITATION = 'createInvitation/LOADING_CREATE_INVITATION';
export const CREATE_INVITATION_SUCCESS = 'createInvitation/CREATE_INVITATION_SUCCESS';
export const CLEAN_CREATE_INVITATION = 'createInvitation/CLEAN_CREATE_INVITATION';
export const LOADING_FAVORITE_USERS = 'createInvitation/LOADING_FAVORITE_USERS';
export const FAVORITE_USERS_AVAILABLE = 'createInvitation/FAVORITE_USERS_AVAILABLE';
export const ADD_USER_TO_INVITED_LIST = 'createInvitation/ADD_USER_TO_INVITED_LIST';
export const REMOVE_USER_FROM_INVITED_LIST = 'createInvitation/REMOVE_USER_FROM_INVITED_LIST';

// export const LOGGED_OUT = logged_out;