export const INVITATION_OUT_AVAILABLE = 'invitations/INVITATION_OUT_AVAILABLE';

export const INVITATION_IN_AVAILABLE = 'invitations/INVITATION_IN_AVAILABLE';
export const LOADING_INVITATION_IN = 'invitations/LOADING_INVITATION_IN';
export const LOADING_FOOTER_INVITATION_IN = 'invitations/LOADING_FOOTER_INVITATION_IN';
export const LOADING_HEADER_INVITATION_IN = 'invitations/LOADING_HEADER_INVITATION_IN';
export const INVITATION_IN_REFRESHED = 'invitations/INVITATION_IN_REFRESHED';
