export const USER_INFO_AVAILABLE = 'profile/USER_INFO_AVAILABLE';
export const LOADING_USER = 'profile/LOADING_USER';
export const UPDATING_USER = 'profile/UPDATING_USER';
export const UPDATED_USER = 'profile/UPDATED_USER';
export const LOADING_ADD_FAVOURITE_USER = 'profile/LOADING_ADD_FAVOURITE_USER';
export const LOADING_DELETE_FAVOURITE_USER = 'profile/LOADING_REMOVE_FAVOURITE_USER';
export const ADD_FAVOURITE_USER = 'profile/ADD_FAVOURITE_USER';
export const REMOVE_FAVOURITE_USER = 'profile/REMOVE_FAVOURITE_USER';
