export const NEW_DIRECT_INVITATION = 'NEW_DIRECT_INVITATION';
export const NEW_MESSAGE = 'NEW_MESSAGE';
export const NEW_FAVOURITE_USER = 'NEW_FAVOURITE_USER';
export const USER_CONFIRMS_ASSISTANCE = 'USER_CONFIRMS_ASSISTANCE';
export const USER_LEFT_INVITATION = 'USER_LEFT_INVITATION';
export const SUGGESTED_CONTEXT_ACTION = 'SUGGESTED_CONTEXT_ACTION';
export const SUGGESTED_EVENT = 'SUGGESTED_EVENT';