export const LOADING_CHAT_LIST = 'chats/LOADING_CHAT_LIST';
export const CHAT_LIST_AVAILABLE = 'chats/CHAT_LIST_AVAILABLE';
export const LOADING_CHAT_MESSAGES = 'chats/LOADING_CHAT_MESSAGES';
export const CHAT_MESSAGES_AVAILABLE = 'chats/CHAT_MESSAGES_AVAILABLE';

export const LOGGED_OUT = 'LOGGED_OUT';